FROM python:3.13-slim

WORKDIR /app
 
COPY . /app

RUN apt update && apt install --no-install-recommends --no-install-suggests -y \
#    git \
    wait-for-it \
    libgl1 \
    libglib2.0-0 \
    libpq-dev \
    zlib1g-dev

RUN pip install --upgrade pip && pip install -r requirements.txt
